relativeURLs = true
title = "Lei Yang"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"

[author]
name = "Lei Yang"
homepage = "http://leiy.me/"

[params]
goatcounter = "leiy"
PGPFingerprint = "2D3EB894C40AE453"
PGPPubkeyLink = "/lei-pgp-pubkey.txt"
shortbio = "Ph.D. in Computer Science"
officeAddress = "Cambridge, MA"
officeMapLink = "https://www.openstreetmap.org/relation/1933745"

[markup]
  [markup.highlight]
    style = "solarized-light"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

